spring.profiles.active: local

# either

defaults:


---

# local file system

spring.profiles: local

defaults:
   destination: ./local


---

# hdfs file system

spring.profiles: hdfs

defaults:
   destination: ./hdfs
