/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package commaweed.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CommaweedChunkContent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6953772441866145350L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CommaweedChunkContent\",\"namespace\":\"commaweed.avro\",\"fields\":[{\"name\":\"bytes\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.nio.ByteBuffer bytes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CommaweedChunkContent() {}

  /**
   * All-args constructor.
   * @param bytes The new value for bytes
   */
  public CommaweedChunkContent(java.nio.ByteBuffer bytes) {
    this.bytes = bytes;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bytes;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bytes = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'bytes' field.
   * @return The value of the 'bytes' field.
   */
  public java.nio.ByteBuffer getBytes() {
    return bytes;
  }

  /**
   * Sets the value of the 'bytes' field.
   * @param value the value to set.
   */
  public void setBytes(java.nio.ByteBuffer value) {
    this.bytes = value;
  }

  /**
   * Creates a new CommaweedChunkContent RecordBuilder.
   * @return A new CommaweedChunkContent RecordBuilder
   */
  public static commaweed.avro.CommaweedChunkContent.Builder newBuilder() {
    return new commaweed.avro.CommaweedChunkContent.Builder();
  }

  /**
   * Creates a new CommaweedChunkContent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CommaweedChunkContent RecordBuilder
   */
  public static commaweed.avro.CommaweedChunkContent.Builder newBuilder(commaweed.avro.CommaweedChunkContent.Builder other) {
    return new commaweed.avro.CommaweedChunkContent.Builder(other);
  }

  /**
   * Creates a new CommaweedChunkContent RecordBuilder by copying an existing CommaweedChunkContent instance.
   * @param other The existing instance to copy.
   * @return A new CommaweedChunkContent RecordBuilder
   */
  public static commaweed.avro.CommaweedChunkContent.Builder newBuilder(commaweed.avro.CommaweedChunkContent other) {
    return new commaweed.avro.CommaweedChunkContent.Builder(other);
  }

  /**
   * RecordBuilder for CommaweedChunkContent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CommaweedChunkContent>
    implements org.apache.avro.data.RecordBuilder<CommaweedChunkContent> {

    private java.nio.ByteBuffer bytes;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(commaweed.avro.CommaweedChunkContent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bytes)) {
        this.bytes = data().deepCopy(fields()[0].schema(), other.bytes);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing CommaweedChunkContent instance
     * @param other The existing instance to copy.
     */
    private Builder(commaweed.avro.CommaweedChunkContent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.bytes)) {
        this.bytes = data().deepCopy(fields()[0].schema(), other.bytes);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'bytes' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getBytes() {
      return bytes;
    }

    /**
      * Sets the value of the 'bytes' field.
      * @param value The value of 'bytes'.
      * @return This builder.
      */
    public commaweed.avro.CommaweedChunkContent.Builder setBytes(java.nio.ByteBuffer value) {
      validate(fields()[0], value);
      this.bytes = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bytes' field has been set.
      * @return True if the 'bytes' field has been set, false otherwise.
      */
    public boolean hasBytes() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bytes' field.
      * @return This builder.
      */
    public commaweed.avro.CommaweedChunkContent.Builder clearBytes() {
      bytes = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public CommaweedChunkContent build() {
      try {
        CommaweedChunkContent record = new CommaweedChunkContent();
        record.bytes = fieldSetFlags()[0] ? this.bytes : (java.nio.ByteBuffer) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
